### ISSUE TITLE
Stuttering issues in certain maps with bots activated

### ISSUE THREAD

**Issue by Riccardoman** [ec-/Quake3e#93] opened 2021-02-18 20:42 UTC
I'm having huge stuttering in this map while playing with bots https://lvlworld.com/download/id:2241

Tested with modded Q3 and vanilla with default cfg

I can confirm for certain that bots are the issue for the stuttering I posted before

Without bots all the maps run flawlessly without any type of stutter

It seems that this map has the most problems with bot pathing https://lvlworld.com/readme/id:2241, in fact on vanilla exe it crashes while loading...
My point is that even on some other maps there is this issue with bots activated, some more than others

[condump.zip](https://github.com/ec-/Quake3e/files/6007691/condump.zip)

**Comment by ec-** [comment] 2021-02-20 16:31
This map is heavy and you're using hdr and msaa on a mobile gpu

**Comment by ec-** [comment] 2021-02-20 16:32
You may also try to use my mini-mod (pak8a.pk3) from there https://github.com/ec-/Quake3e/releases/download/2020-10-31/quake3-1.32e-20201031.zip

**Comment by Riccardoman** [comment] 2021-02-21 03:34
The mouse is incredibly smooth with your mod! Btw should I use the exe inside your mini mod or can I update them with the exe in your latest release?

**Comment by Riccardoman** [comment] 2021-02-21 19:31
I just managed to run those maps on vanilla quake3.exe, with vanilla and spearmint I have no issues, only with quake3e

**Comment by ec-** [comment] 2021-02-22 06:17
Try `\r_fbo 0; vid_restart`

**Comment by Riccardoman** [comment] 2021-02-22 13:37
I tried it but without luck, with or without fbo features the game in those maps stutters

**Comment by ec-** [comment] 2021-02-22 15:37
Doest it stutters on a recorded demo too?

**Comment by Riccardoman** [comment] 2021-02-22 17:24
Thanks for the suggestion! I found something really interesting
[demo1.zip](https://github.com/ec-/Quake3e/files/6023860/demo1.zip)
It says connection interrupted

**Comment by ec-** [comment] 2021-02-22 20:06
So it is something with server-side code, can you show your server configuration or q3config.cfg?

**Comment by Riccardoman** [comment] 2021-02-22 20:55
This is my current cfg
[q3config.zip](https://github.com/ec-/Quake3e/files/6025082/q3config.zip)

**Comment by ec-** [comment] 2021-02-23 11:32
I see only `r_swapInterval 1` suspicious, next step - try to launch dedicated server binary (quake3.ded.x64), run map with bots and connect to this server as regual client, then look in task manager to see which process takes most of the cpu time

**Comment by Riccardoman** [comment] 2021-02-23 15:33
This is what I got
![Screenshot (1335)](https://user-images.githubusercontent.com/74624503/108866826-d7ec7500-75f4-11eb-9c06-b3e267c99d30.jpg)

[demo.zip](https://github.com/ec-/Quake3e/files/6029925/demo.zip)

**Comment by Riccardoman** [comment] 2021-02-23 21:39
Also about your mod: is it possible to make the music NOT restart after the warmup?

**Comment by ec-** [comment] 2021-02-24 18:55
I can't reproduce such high cpu usage on my system, it barely hits 5-10% with 20 bots on `dk_msg4_ctf`

Warmup & related stuff is controlled by mod

**Comment by Riccardoman** [comment] 2021-02-24 19:02
Ok that's my CPU fault. Probably my system is managing it very badly, or a core is defective

**Comment by ec-** [comment] 2021-02-24 19:10
https://github.com/ec-/baseq3a/blob/master/code/cgame/cg_servercmds.c#L461

**Comment by Riccardoman** [comment] 2021-02-24 20:56
Thanks

I have one last favor to ask. If you could test the maps with the custom folder I made https://mega.nz/folder/Pp0ykSxa#5NdubKrpz1dNRfWQpgMrSg

To understand If I messed up something in the game or it is my CPU

The maps lostparadise and overgrowth are in the pk3 named MCTF 1-Q inside the baseq3\maps folder

Thank you for your patience

**Comment by ec-** [comment] 2021-02-25 12:51
This should be fixed with recent commit.

Also, remove public access to your files as it is illegal to share copyrighted material

**Comment by Riccardoman** [comment] 2021-03-01 12:23
I just tried your latest release but nothing has changed for me in these 3 maps

**Comment by Riccardoman** [comment] 2021-03-02 15:02
To be honest I don't want to give you an issue if that's only on my end because I messed up my game files
Do you still have the link I sent you? Try to test it on your system to be sure

**Comment by Riccardoman** [comment] 2021-03-13 15:28
I can confirm that the stuttering problem is directly associated with the aas botfile. And I think it's also related by it's size
I just recently created a botfile for the map moonstone that has the biggest size compared to the 500+ maps that I have installed and immediately when I start the map with bots the game freezes

**Comment by ec-** [comment] 2021-03-13 17:09
I'm changed max.cache to what I observed on `dk_msg4_ctf`

**Comment by Riccardoman** [comment] 2021-03-14 10:34
Yes I can confirm that now there's no more stuttering. Just occasionally each 30s-1m one little stutter. But now the maps are absolutely playable! Thanks
(For "moonstone" the aas is 18mb, so I gave up installing that map)

**Closed** 2021-03-14 10:34 UTC
